export const cakes = [
  // Wedding Cakes
  {
    id: 1,
    name: "Rustic Wedding Cake",
    price: 20,
    image: "/images/cake 9.jpeg",
    description: "Bride And Groom Holding Hands Rustic Wedding Cake Toppers Anniversary Cake Toppers Wedding Cake Decorations Engagement Cake Topper Acrylic Black Custom Couple Name Cake Toppers.",
    category: "Wedding",
  },
  {
    id: 2,
    name: "Elegant Designer Wedding Cake",
    price: 24,
    image: "/images/cake 8.jpeg",
    description: "Elevate your wedding with our Elegant Designer Wedding Cake 6kg! This beautifully crafted cake is perfect for adding a touch of luxury to your special day. Order now from Cake Square Chennai and make your celebration truly unforgettable!.",
    category: "Wedding",
  },
  {
    id: 3,
    name: "Elegant Two Tier Wedding Cake",
    price: 24,
    image: "/images/cake 7.jpeg",
    description: "Design and icing of cake may very from the image shown here since each chef has his/her own way of baking and designing a cake.",
    category: "Wedding",
  },
  {
    id: 4,
    name: "Red velvet Wedding Cake",
    price: 10,
    image: "/images/cake 4.jpeg",
    description: "It is necessary to show your love to your dear ones so that your relationship always has a strong bond of affection and trust. Gift online this very amazing valentine red velvet cake of half kg the special one, along with a lovely personalized message. It is available in all basic flavors.",
    category: "Wedding",
  },
  // Birthday Cakes
  {
    id: 5,
    name: "Chocolate Cake",
    price: 6,
    image: "/images/cake 1.jpeg",
    description: "A rich chocolate cake perfect for any birthday celebration.",
    category: "Birthday",
  },
  {
    id: 6,
    name: "Venilla Fruit Cake",
    price: 10,
    image: "/images/cake 2.jpeg",
    description: "Vanilla fruit cake is a light and flavorful dessert combining moist vanilla sponge with a medley of fresh fruits for a refreshing treat.",
    category: "Birthday",
  },
  {
    id: 7,
    name: "Red velvet Cake",
    price: 8,
    image: "/images/cake 4.1.jpeg",
    description: "Red velvet cake is a soft, velvety dessert with a hint of cocoa, layered with creamy cream cheese frosting and a signature red hue.",
    category: "Birthday",
  },
  {
    id: 8,
    name: "Blackcurrent Cake",
    price: 10,
    image: "/images/cake 5.jpeg",
    description: "Blackcurrant cake is a fruity dessert with moist layers infused with blackcurrant flavor, complemented by sweet-tart blackcurrant frosting.",
    category: "Birthday",
  },
  {
    id: 9,
    name: "Butterscotch",
    price: 10,
    image: "/images/cake3.1.jpeg",
    description: "Butterscotch cake is a rich and creamy dessert featuring layers of caramel-flavored cake and butterscotch frosting, topped with crunchy toffee bits.",
    category: "Birthday",
  },
  {
    id: 10,
    name: "Almond cake",
    price: 12,
    image: "/images/cake 4.1.jpeg",
    description: "Almond cake is a moist and nutty dessert made with ground almonds, offering a rich flavor and delicate texture.",
    category: "Birthday",
  },
  {
    id: 11,
    name: "Oreo cake",
    price: 8,
    image: "/images/cake oreo.jpeg",
    description: "Oreo cake is a decadent dessert combining moist chocolate layers with Oreo-flavored frosting and crushed cookie topping.",
    category: "Birthday",
  },
  // Special cakes
  {
    id: 12,
    name: "Spiderman cake",
    price: 15,
    image: "/images/cake 10 sm.jpeg",
    description: "Let your child’s birthday be a superhero adventure with our Spider Man Theme Birthday Cake  this cake captures the excitement of Spider-Man with his iconic mask and web-slinging design.",
    category: "Special",
  },
  {
    id: 13,
    name: "Drwate Mermaid cake Topper",
    price: 20,
    image: "/images/cake 11 drwate mermaid cake topper.jpeg",
    description: "his set of mermaid themed birthday party cake toppers picks is especially designed for ocean theme birthday party, well made and adorable. They will be the perfect addition to your party!.",
    category: "Special",
  },
  {
    id: 14,
    name: "doll cake",
    price: 15,
    image: "/images/cake 12.jpeg",
    description: "Every first birthday is a milestone worth celebrating in grand style. Our 1st birthday cakes are designed to make your little one’s special day memorable. With a wide range of themes and flavors, our cakes are sure to delight both kids and adults.",
    category: "Special",
  },
  {
    id: 15,
    name: "doll cake",
    price: 20,
    image: "/images/CAKE 13.jpeg",
    description: "Eggless cake. Make your childs birthday celebration super special with this customised doll cake.",
    category: "Special",
  },
];